### ISSUE TITLE
Can't install Stacer with Node 7.1.0

### ISSUE THREAD

**Issue by SalahAdDin** [oguzhaninan/Stacer#46]
Hi, your project looks great, for this reason i tried to install it, but i get one error: it couldn't be installed with `npm` or from `AUR`.

My system is `Antergos`, so use `Arch` core.

I have this `log` from `npm install`:
```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install' ]
2 info using npm@4.5.0
3 info using node@v7.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData fsevents
20 silly mapToRegistry name fsevents
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry data Result {
23 silly mapToRegistry   raw: 'fsevents',
23 silly mapToRegistry   scope: null,
23 silly mapToRegistry   escapedName: 'fsevents',
23 silly mapToRegistry   name: 'fsevents',
23 silly mapToRegistry   rawSpec: '',
23 silly mapToRegistry   spec: 'latest',
23 silly mapToRegistry   type: 'tag' }
24 silly mapToRegistry uri https://registry.npmjs.org/fsevents
25 verbose request uri https://registry.npmjs.org/fsevents
26 verbose request no auth needed
27 info attempt registry request try #1 at 20:14:39
28 verbose request id 2b1ed2877a9cc4ce
29 verbose etag "A234G4D80YWPFVQ48CZDVPH48"
30 http request GET https://registry.npmjs.org/fsevents
31 http 200 https://registry.npmjs.org/fsevents
32 verbose headers { server: 'nginx/1.10.1',
32 verbose headers   'content-type': 'application/json',
32 verbose headers   'last-modified': 'Fri, 17 Mar 2017 13:17:09 GMT',
32 verbose headers   etag: 'W/"58cbe1d5-d5e6"',
32 verbose headers   'content-encoding': 'gzip',
32 verbose headers   'cache-control': 'max-age=300',
32 verbose headers   'content-length': '6671',
32 verbose headers   'accept-ranges': 'bytes',
32 verbose headers   date: 'Fri, 12 May 2017 00:14:40 GMT',
32 verbose headers   via: '1.1 varnish',
32 verbose headers   age: '63',
32 verbose headers   connection: 'keep-alive',
32 verbose headers   'x-served-by': 'cache-sjc3623-SJC',
32 verbose headers   'x-cache': 'HIT',
32 verbose headers   'x-cache-hits': '4',
32 verbose headers   'x-timer': 'S1494548081.744456,VS0,VE0',
32 verbose headers   vary: 'Accept-Encoding' }
33 silly get cb [ 200,
33 silly get   { server: 'nginx/1.10.1',
33 silly get     'content-type': 'application/json',
33 silly get     'last-modified': 'Fri, 17 Mar 2017 13:17:09 GMT',
33 silly get     etag: 'W/"58cbe1d5-d5e6"',
33 silly get     'content-encoding': 'gzip',
33 silly get     'cache-control': 'max-age=300',
33 silly get     'content-length': '6671',
33 silly get     'accept-ranges': 'bytes',
33 silly get     date: 'Fri, 12 May 2017 00:14:40 GMT',
33 silly get     via: '1.1 varnish',
33 silly get     age: '63',
33 silly get     connection: 'keep-alive',
33 silly get     'x-served-by': 'cache-sjc3623-SJC',
33 silly get     'x-cache': 'HIT',
33 silly get     'x-cache-hits': '4',
33 silly get     'x-timer': 'S1494548081.744456,VS0,VE0',
33 silly get     vary: 'Accept-Encoding' } ]
34 verbose get saving fsevents to /home/alfredo/.npm/registry.npmjs.org/fsevents/.cache.json
35 verbose correctMkdir /home/alfredo/.npm correctMkdir not in flight; initializing
36 silly pickManifestFromRegistryMetadata spec >=1.0.0 <2.0.0 tag latest versions [ '0.1.1',
36 silly pickManifestFromRegistryMetadata   '0.1.3',
36 silly pickManifestFromRegistryMetadata   '0.1.4',
36 silly pickManifestFromRegistryMetadata   '0.1.5',
36 silly pickManifestFromRegistryMetadata   '0.1.6',
36 silly pickManifestFromRegistryMetadata   '0.2.0',
36 silly pickManifestFromRegistryMetadata   '0.3.0',
36 silly pickManifestFromRegistryMetadata   '0.3.1',
36 silly pickManifestFromRegistryMetadata   '0.3.2',
36 silly pickManifestFromRegistryMetadata   '0.3.3',
36 silly pickManifestFromRegistryMetadata   '0.3.4',
36 silly pickManifestFromRegistryMetadata   '0.3.5',
36 silly pickManifestFromRegistryMetadata   '0.3.6',
36 silly pickManifestFromRegistryMetadata   '0.3.7',
36 silly pickManifestFromRegistryMetadata   '0.3.8',
36 silly pickManifestFromRegistryMetadata   '1.0.0',
36 silly pickManifestFromRegistryMetadata   '1.0.1',
36 silly pickManifestFromRegistryMetadata   '1.0.2',
36 silly pickManifestFromRegistryMetadata   '1.0.3',
36 silly pickManifestFromRegistryMetadata   '1.0.4',
36 silly pickManifestFromRegistryMetadata   '1.0.5',
36 silly pickManifestFromRegistryMetadata   '1.0.6',
36 silly pickManifestFromRegistryMetadata   '1.0.7',
36 silly pickManifestFromRegistryMetadata   '1.0.8',
36 silly pickManifestFromRegistryMetadata   '1.0.9',
36 silly pickManifestFromRegistryMetadata   '1.0.10',
36 silly pickManifestFromRegistryMetadata   '1.0.11',
36 silly pickManifestFromRegistryMetadata   '1.0.12',
36 silly pickManifestFromRegistryMetadata   '1.0.14',
36 silly pickManifestFromRegistryMetadata   '1.0.15',
36 silly pickManifestFromRegistryMetadata   '1.0.17',
36 silly pickManifestFromRegistryMetadata   '1.0.18-0',
36 silly pickManifestFromRegistryMetadata   '1.1.0',
36 silly pickManifestFromRegistryMetadata   '1.1.1' ]
37 silly resolveWithNewModule fsevents@1.1.1 checking installable status
38 silly loadAllDepsIntoIdealTree Finishing
39 silly loadIdealTree Finishing
40 silly currentTree Stacer@1.0.6
40 silly currentTree ansi-regex@2.1.1
40 silly currentTree anymatch@1.3.0
40 silly currentTree arr-flatten@1.0.3
40 silly currentTree array-unique@0.2.1
40 silly currentTree asn1@0.2.3
40 silly currentTree async-each@1.0.1
40 silly currentTree aws-sign2@0.6.0
40 silly currentTree babel-cli@6.24.1
40 silly currentTree babel-core@6.24.1
40 silly currentTree babel-helper-call-delegate@6.24.1
40 silly currentTree babel-helper-function-name@6.24.1
40 silly currentTree babel-helper-hoist-variables@6.24.1
40 silly currentTree babel-helper-regex@6.24.1
40 silly currentTree babel-helpers@6.24.1
40 silly currentTree babel-plugin-check-es2015-constants@6.22.0
40 silly currentTree babel-plugin-transform-es2015-block-scoped-functions@6.22.0
40 silly currentTree babel-plugin-transform-es2015-classes@6.24.1
40 silly currentTree babel-plugin-transform-es2015-destructuring@6.23.0
40 silly currentTree babel-plugin-transform-es2015-for-of@6.23.0
40 silly currentTree babel-plugin-transform-es2015-literals@6.22.0
40 silly currentTree babel-plugin-transform-es2015-modules-commonjs@6.24.1
40 silly currentTree babel-plugin-transform-es2015-modules-umd@6.24.1
40 silly currentTree babel-plugin-transform-es2015-parameters@6.24.1
40 silly currentTree babel-plugin-transform-es2015-spread@6.22.0
40 silly currentTree babel-plugin-transform-es2015-template-literals@6.22.0
40 silly currentTree babel-plugin-transform-es2015-unicode-regex@6.24.1
40 silly currentTree babel-plugin-transform-strict-mode@6.24.1
40 silly currentTree babel-preset-es2015@6.24.1
40 silly currentTree babel-runtime@6.23.0
40 silly currentTree babel-traverse@6.24.1
40 silly currentTree babylon@6.17.1
40 silly currentTree bcrypt-pbkdf@1.0.1
40 silly currentTree boom@2.10.1
40 silly currentTree braces@1.8.5
40 silly currentTree builtin-modules@1.1.1
40 silly currentTree camelcase@2.1.1
40 silly currentTree chalk@1.1.3
40 silly currentTree chartjs-color-string@0.4.0
40 silly currentTree chartkick@2.2.3
40 silly currentTree co@4.6.0
40 silly currentTree color-convert@0.5.3
40 silly currentTree combined-stream@1.0.5
40 silly currentTree concat-map@0.0.1
40 silly currentTree convert-source-map@1.5.0
40 silly currentTree core-util-is@1.0.2
40 silly currentTree currently-unhandled@0.4.1
40 silly currentTree debug@2.6.6
40 silly currentTree deep-extend@0.4.2
40 silly currentTree detect-indent@4.0.0
40 silly currentTree electron-download@3.3.0
40 silly currentTree minimist@1.2.0
40 silly currentTree error-ex@1.3.1
40 silly currentTree escape-string-regexp@1.0.5
40 silly currentTree expand-brackets@0.1.5
40 silly currentTree extend@3.0.1
40 silly currentTree extract-zip@1.6.5
40 silly currentTree debug@2.2.0
40 silly currentTree mkdirp@0.5.0
40 silly currentTree ms@0.7.1
40 silly currentTree fd-slicer@1.0.1
40 silly currentTree fill-range@2.2.3
40 silly currentTree for-in@1.0.2
40 silly currentTree forever-agent@0.6.1
40 silly currentTree fs-extra@0.30.0
40 silly currentTree fs.realpath@1.0.0
40 silly currentTree getpass@0.1.7
40 silly currentTree assert-plus@1.0.0
40 silly currentTree glob-parent@2.0.0
40 silly currentTree globals@9.17.0
40 silly currentTree graceful-readlink@1.0.1
40 silly currentTree har-validator@4.2.1
40 silly currentTree hawk@3.1.3
40 silly currentTree home-or-tmp@2.0.0
40 silly currentTree hosted-git-info@2.4.2
40 silly currentTree indent-string@2.1.0
40 silly currentTree inherits@2.0.3
40 silly currentTree invariant@2.2.2
40 silly currentTree is-binary-path@1.0.1
40 silly currentTree is-builtin-module@1.0.0
40 silly currentTree is-equal-shallow@0.1.3
40 silly currentTree is-extglob@1.0.0
40 silly currentTree is-fullwidth-code-point@1.0.0
40 silly currentTree is-number@2.1.0
40 silly currentTree is-primitive@2.0.0
40 silly currentTree is-utf8@0.2.1
40 silly currentTree isobject@2.1.0
40 silly currentTree jodid25519@1.0.2
40 silly currentTree js-tokens@3.0.1
40 silly currentTree jsesc@1.3.0
40 silly currentTree json-stable-stringify@1.0.1
40 silly currentTree json5@0.5.1
40 silly currentTree jsonify@0.0.0
40 silly currentTree kind-of@3.2.0
40 silly currentTree load-json-file@1.1.0
40 silly currentTree loose-envify@1.3.1
40 silly currentTree map-obj@1.0.1
40 silly currentTree micromatch@2.3.11
40 silly currentTree mime-types@2.1.15
40 silly currentTree minimist@0.0.8
40 silly currentTree moment@2.18.1
40 silly currentTree normalize-package-data@2.3.8
40 silly currentTree nugget@2.0.1
40 silly currentTree minimist@1.2.0
40 silly currentTree oauth-sign@0.8.2
40 silly currentTree object-keys@0.4.0
40 silly currentTree once@1.4.0
40 silly currentTree os-tmpdir@1.0.2
40 silly currentTree parse-glob@3.0.4
40 silly currentTree path-exists@2.1.0
40 silly currentTree path-type@1.1.0
40 silly currentTree performance-now@0.2.0
40 silly currentTree pinkie-promise@2.0.1
40 silly currentTree preserve@0.2.0
40 silly currentTree private@0.1.7
40 silly currentTree progress-stream@1.2.0
40 silly currentTree properties-reader@0.0.15
40 silly currentTree qs@6.4.0
40 silly currentTree rc@1.2.1
40 silly currentTree minimist@1.2.0
40 silly currentTree read-pkg@1.1.0
40 silly currentTree readdirp@2.1.0
40 silly currentTree regenerate@1.3.2
40 silly currentTree regenerator-transform@0.9.11
40 silly currentTree regexpu-core@2.0.0
40 silly currentTree regjsparser@0.1.5
40 silly currentTree jsesc@0.5.0
40 silly currentTree repeat-element@1.1.2
40 silly currentTree repeating@2.0.1
40 silly currentTree rimraf@2.6.1
40 silly currentTree semver@5.3.0
40 silly currentTree shifty@1.5.4
40 silly currentTree single-line-log@1.1.2
40 silly currentTree sntp@1.0.9
40 silly currentTree source-map@0.5.6
40 silly currentTree spdx-expression-parse@1.0.4
40 silly currentTree speedometer@0.1.4
40 silly currentTree string_decoder@1.0.0
40 silly currentTree stringstream@0.0.5
40 silly currentTree strip-bom@2.0.0
40 silly currentTree strip-json-comments@2.0.1
40 silly currentTree sumchecker@1.3.1
40 silly currentTree systeminformation@3.17.3
40 silly currentTree through2@0.2.3
40 silly currentTree isarray@0.0.1
40 silly currentTree readable-stream@1.1.14
40 silly currentTree string_decoder@0.10.31
40 silly currentTree tough-cookie@2.3.2
40 silly currentTree trim-right@1.0.1
40 silly currentTree tweetnacl@0.14.5
40 silly currentTree user-home@1.1.1
40 silly currentTree uuid@3.0.1
40 silly currentTree validate-npm-package-license@3.0.1
40 silly currentTree vuex@2.3.1
40 silly currentTree xtend@2.1.2
40 silly currentTree ajv@4.11.8
41 silly idealTree ansi-styles@2.2.1
41 silly idealTree arr-diff@2.0.0
41 silly idealTree array-find-index@1.0.2
41 silly idealTree arrify@1.0.1
41 silly idealTree assert-plus@0.2.0
41 silly idealTree asynckit@0.4.0
41 silly idealTree aws4@1.6.0
41 silly idealTree babel-code-frame@6.22.0
41 silly idealTree babel-generator@6.24.1
41 silly idealTree babel-helper-define-map@6.24.1
41 silly idealTree babel-helper-get-function-arity@6.24.1
41 silly idealTree babel-helper-optimise-call-expression@6.24.1
41 silly idealTree babel-helper-replace-supers@6.24.1
41 silly idealTree babel-messages@6.23.0
41 silly idealTree babel-plugin-transform-es2015-arrow-functions@6.22.0
41 silly idealTree babel-plugin-transform-es2015-block-scoping@6.24.1
41 silly idealTree babel-plugin-transform-es2015-computed-properties@6.24.1
41 silly idealTree babel-plugin-transform-es2015-duplicate-keys@6.24.1
41 silly idealTree babel-plugin-transform-es2015-function-name@6.24.1
41 silly idealTree babel-plugin-transform-es2015-modules-amd@6.24.1
41 silly idealTree babel-plugin-transform-es2015-modules-systemjs@6.24.1
41 silly idealTree babel-plugin-transform-es2015-object-super@6.24.1
41 silly idealTree babel-plugin-transform-es2015-shorthand-properties@6.24.1
41 silly idealTree babel-plugin-transform-es2015-sticky-regex@6.24.1
41 silly idealTree babel-plugin-transform-es2015-typeof-symbol@6.23.0
41 silly idealTree babel-plugin-transform-regenerator@6.24.1
41 silly idealTree babel-polyfill@6.23.0
41 silly idealTree babel-register@6.24.1
41 silly idealTree mkdirp@0.5.1
41 silly idealTree babel-template@6.24.1
41 silly idealTree babel-types@6.24.1
41 silly idealTree balanced-match@0.4.2
41 silly idealTree binary-extensions@1.8.0
41 silly idealTree brace-expansion@1.1.7
41 silly idealTree buffer-shims@1.0.0
41 silly idealTree camelcase-keys@2.1.0
41 silly idealTree caseless@0.12.0
41 silly idealTree chart.js@2.5.0
41 silly idealTree chartjs-color@2.1.0
41 silly idealTree chokidar@1.7.0
41 silly idealTree code-point-at@1.1.0
41 silly idealTree color-name@1.1.2
41 silly idealTree commander@2.9.0
41 silly idealTree concat-stream@1.6.0
41 silly idealTree core-js@2.4.1
41 silly idealTree cryptiles@2.0.5
41 silly idealTree dashdash@1.14.1
41 silly idealTree assert-plus@1.0.0
41 silly idealTree decamelize@1.2.0
41 silly idealTree delayed-stream@1.0.0
41 silly idealTree ecc-jsbn@0.1.1
41 silly idealTree electron@1.6.7
41 silly idealTree es6-promise@4.1.0
41 silly idealTree esutils@2.0.2
41 silly idealTree expand-range@1.8.2
41 silly idealTree extglob@0.3.2
41 silly idealTree extsprintf@1.0.2
41 silly idealTree filename-regex@2.0.1
41 silly idealTree find-up@1.1.2
41 silly idealTree for-own@0.1.5
41 silly idealTree form-data@2.1.4
41 silly idealTree fs-readdir-recursive@1.0.0
41 silly idealTree get-stdin@4.0.1
41 silly idealTree glob-base@0.3.0
41 silly idealTree glob@7.1.1
41 silly idealTree graceful-fs@4.1.11
41 silly idealTree har-schema@1.0.5
41 silly idealTree has-ansi@2.0.0
41 silly idealTree hoek@2.16.3
41 silly idealTree home-path@1.0.5
41 silly idealTree http-signature@1.1.1
41 silly idealTree inflight@1.0.6
41 silly idealTree ini@1.3.4
41 silly idealTree is-arrayish@0.2.1
41 silly idealTree is-buffer@1.1.5
41 silly idealTree is-dotfile@1.0.2
41 silly idealTree is-extendable@0.1.1
41 silly idealTree is-finite@1.0.2
41 silly idealTree is-glob@2.0.1
41 silly idealTree is-posix-bracket@0.1.1
41 silly idealTree is-typedarray@1.0.0
41 silly idealTree isarray@1.0.0
41 silly idealTree isstream@0.1.2
41 silly idealTree jquery@3.2.1
41 silly idealTree jsbn@0.1.1
41 silly idealTree json-schema@0.2.3
41 silly idealTree json-stringify-safe@5.0.1
41 silly idealTree jsonfile@2.4.0
41 silly idealTree jsprim@1.4.0
41 silly idealTree assert-plus@1.0.0
41 silly idealTree klaw@1.3.1
41 silly idealTree lodash@4.17.4
41 silly idealTree loud-rejection@1.6.0
41 silly idealTree meow@3.7.0
41 silly idealTree minimist@1.2.0
41 silly idealTree mime-db@1.27.0
41 silly idealTree minimatch@3.0.4
41 silly idealTree mkdirp@0.3.5
41 silly idealTree ms@0.7.3
41 silly idealTree normalize-path@2.1.1
41 silly idealTree number-is-nan@1.0.1
41 silly idealTree object-assign@4.1.1
41 silly idealTree object.omit@2.0.1
41 silly idealTree os-homedir@1.0.2
41 silly idealTree output-file-sync@1.1.2
41 silly idealTree mkdirp@0.5.1
41 silly idealTree parse-json@2.2.0
41 silly idealTree path-is-absolute@1.0.1
41 silly idealTree pend@1.2.0
41 silly idealTree pify@2.3.0
41 silly idealTree pinkie@2.0.4
41 silly idealTree pretty-bytes@1.0.4
41 silly idealTree process-nextick-args@1.0.7
41 silly idealTree progressbar.js@1.0.1
41 silly idealTree punycode@1.4.1
41 silly idealTree randomatic@1.1.6
41 silly idealTree read-pkg-up@1.0.1
41 silly idealTree readable-stream@2.2.9
41 silly idealTree redent@1.0.0
41 silly idealTree regenerator-runtime@0.10.5
41 silly idealTree regex-cache@0.4.3
41 silly idealTree regjsgen@0.2.0
41 silly idealTree remove-trailing-separator@1.0.1
41 silly idealTree repeat-string@1.6.1
41 silly idealTree request@2.81.0
41 silly idealTree safe-buffer@5.0.1
41 silly idealTree set-immediate-shim@1.0.1
41 silly idealTree signal-exit@3.0.2
41 silly idealTree slash@1.0.0
41 silly idealTree source-map-support@0.4.15
41 silly idealTree spdx-correct@1.0.2
41 silly idealTree spdx-license-ids@1.2.2
41 silly idealTree sshpk@1.13.0
41 silly idealTree assert-plus@1.0.0
41 silly idealTree string-width@1.0.2
41 silly idealTree strip-ansi@3.0.1
41 silly idealTree strip-indent@1.0.1
41 silly idealTree sudo-prompt@6.2.1
41 silly idealTree supports-color@2.0.0
41 silly idealTree throttleit@0.0.2
41 silly idealTree to-fast-properties@1.0.3
41 silly idealTree trim-newlines@1.0.0
41 silly idealTree tunnel-agent@0.6.0
41 silly idealTree typedarray@0.0.6
41 silly idealTree util-deprecate@1.0.2
41 silly idealTree v8flags@2.1.1
41 silly idealTree verror@1.3.6
41 silly idealTree wrappy@1.0.2
41 silly idealTree yauzl@2.4.1
42 silly generateActionsToTake Starting
43 silly install generateActionsToTake
44 silly generateActionsToTake Finishing
45 silly diffTrees action count 0
46 silly decomposeActions action count 0
47 silly runTopLevelLifecycles Starting
48 silly install runPreinstallTopLevelLifecycles
49 silly preinstall Stacer@1.0.6
50 info lifecycle Stacer@1.0.6~preinstall: Stacer@1.0.6
51 silly lifecycle Stacer@1.0.6~preinstall: no script for preinstall, continuing
52 silly executeActions Starting
53 silly install executeActions
54 silly doSerial global-install 0
55 silly doParallel fetch 0
56 verbose correctMkdir /home/alfredo/.npm/_locks correctMkdir not in flight; initializing
57 verbose lock using /home/alfredo/.npm/_locks/staging-3769f8e282723f72.lock for /home/alfredo/Stacer/node_modules/.staging
58 verbose unlock done using /home/alfredo/.npm/_locks/staging-3769f8e282723f72.lock for /home/alfredo/Stacer/node_modules/.staging
59 silly rollbackFailedOptional Starting
60 silly rollbackFailedOptional Finishing
61 silly runTopLevelLifecycles Finishing
62 silly install printInstalled
63 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
64 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
65 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
65 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
65 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
65 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
66 verbose stack Error: EACCES: permission denied, mkdir '/home/alfredo/Stacer/node_modules/.staging'
67 verbose cwd /home/alfredo/Stacer
68 verbose Linux 4.10.13-1-ARCH
69 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
70 verbose node v7.10.0
71 verbose npm  v4.5.0
72 error path /home/alfredo/Stacer/node_modules/.staging
73 error code EACCES
74 error errno -13
75 error syscall mkdir
76 error Error: EACCES: permission denied, mkdir '/home/alfredo/Stacer/node_modules/.staging'
76 error  { Error: EACCES: permission denied, mkdir '/home/alfredo/Stacer/node_modules/.staging'
76 error   errno: -13,
76 error   code: 'EACCES',
76 error   syscall: 'mkdir',
76 error   path: '/home/alfredo/Stacer/node_modules/.staging' }
77 error Please try running this command again as root/Administrator.
78 verbose exit [ -13, true ]
```
And this from `npm build`:
```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@4.5.0
3 info using node@v7.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle Stacer@1.0.6~prebuild: Stacer@1.0.6
6 silly lifecycle Stacer@1.0.6~prebuild: no script for prebuild, continuing
7 info lifecycle Stacer@1.0.6~build: Stacer@1.0.6
8 verbose lifecycle Stacer@1.0.6~build: unsafe-perm in lifecycle true
9 verbose lifecycle Stacer@1.0.6~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/alfredo/Stacer/node_modules/.bin:/home/alfredo/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
10 verbose lifecycle Stacer@1.0.6~build: CWD: /home/alfredo/Stacer
11 silly lifecycle Stacer@1.0.6~build: Args: [ '-c', 'babel src/ -d bundle/' ]
12 silly lifecycle Stacer@1.0.6~build: Returned: code: 1  signal: null
13 info lifecycle Stacer@1.0.6~build: Failed to exec build script
14 verbose stack Error: Stacer@1.0.6 build: `babel src/ -d bundle/`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid Stacer@1.0.6
16 verbose cwd /home/alfredo/Stacer
17 verbose Linux 4.10.13-1-ARCH
18 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
19 verbose node v7.10.0
20 verbose npm  v4.5.0
21 error code ELIFECYCLE
22 error errno 1
23 error Stacer@1.0.6 build: `babel src/ -d bundle/`
23 error Exit status 1
24 error Failed at the Stacer@1.0.6 build script 'babel src/ -d bundle/'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the Stacer package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     babel src/ -d bundle/
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs Stacer
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls Stacer
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

What's the problem?

Thanks.

**Comment by SalahAdDin** [comment]
_UPDATE_:
After one half hour i could install it. Why take one hour for do it?
This is my technical specification:
```bash
               `.-/::/-``                
            .-/osssssssso/.               salahaddin@TulipanROG
           :osyysssssssyyys+-             OS: Antergos  ISO-Rolling
        `.+yyyysssssssssyyyyy+.           Kernel: x86_64 Linux 4.10.13-1-ARCH
       `/syyyyyssssssssssyyyyys-`         Uptime: 48m
      `/yhyyyyysss++ssosyyyyhhy/`         Packages: 1268
     .ohhhyyyyso++/+oso+syy+shhhho.       Shell: zsh 5.3.1
    .shhhhysoo++//+sss+++yyy+shhhhs.      Resolution: 1920x1080
   -yhhhhs+++++++ossso+++yyys+ohhddy:     DE: GNOME 
  -yddhhyo+++++osyyss++++yyyyooyhdddy-    WM: GNOME Shell
 .yddddhso++osyyyyys+++++yyhhsoshddddy`   WM Theme: Numix-Frost
`odddddhyosyhyyyyyy++++++yhhhyosddddddo   GTK Theme: Numix-Frost-Light [GTK2/3]
.dmdddddhhhhhhhyyyo+++++shhhhhohddddmmh.  Icon Theme: Numix-Square
ddmmdddddhhhhhhhso++++++yhhhhhhdddddmmdy  Font: Cantarell 11
dmmmdddddddhhhyso++++++shhhhhddddddmmmmh  CPU: Intel Core i7-4720HQ @ 8x 3.6GHz [53.0°C]
-dmmmdddddddhhyso++++oshhhhdddddddmmmmd-  GPU: intel
 .smmmmddddddddhhhhhhhhhdddddddddmmmms.   RAM: 1727MiB / 15941MiB
npm -v  
4.5.0
node -v   
v7.10.0
```

**Comment by oguzhaninan** [comment]
It must be your Internet speed.  I recommend you to use [yarn](https://yarnpkg.com/en/).
